### ISSUE TITLE
Feb 2021 Improvements 

### ISSUE THREAD

**Issue by nervewax** [mkdo/mkdo-base#43]
> For help fleshing out this issue see: http://extranet.makedo.net/github-issues/

**Summary of the task**  
Apply changes and fixes that have been identified in other projects.

**Internal notes**  
...

**To-do list**  

- [x] Move asset enqueue to separate js file to cut down outputted js in footer.js
- [x] Properly enqueue admin css and js
- [x] Update all webpack deps
- [x] Fix all resulting issues and update tools to work with new deps

**Criteria to meet**  

...

**Supporting visuals or documents**  
...
